/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.12
 * Generated at: 2023-12-08 05:52:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import project.SleepCalculator;
import project.CaloriesCalculator;
import project.IllnessCalculator;

public final class index2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("project.SleepCalculator");
    _jspx_imports_classes.add("project.CaloriesCalculator");
    _jspx_imports_classes.add("project.IllnessCalculator");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("  \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("      <html>\r\n");
      out.write("\r\n");
      out.write("      <head>\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("        <title>Your Health Dashboard</title>\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Montserrat\">\r\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"styles2.css\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("        <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>\r\n");
      out.write("	\r\n");
      out.write("<script>\r\n");
      out.write("  // Use fetch to trigger the SleepAnalyticsServlet on page load\r\n");
      out.write("  function fetchSleepAnalytics() {\r\n");
      out.write("    fetch('SleepAnalyticsServlet')\r\n");
      out.write("      .then(response => response.text())\r\n");
      out.write("      .then(data => {\r\n");
      out.write("        // Optional: You can add logic to update the UI based on the response from the servlet\r\n");
      out.write("        console.log(data);\r\n");
      out.write("      })\r\n");
      out.write("      .catch(error => {\r\n");
      out.write("        console.error('Error:', error);\r\n");
      out.write("      });\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  function submitForm() {\r\n");
      out.write("    var inputValue = document.getElementById(\"inputValue\").value;\r\n");
      out.write("\r\n");
      out.write("    fetch('SaveToDatabaseServlet', {\r\n");
      out.write("      method: 'POST',\r\n");
      out.write("      headers: {\r\n");
      out.write("        'Content-Type': 'application/x-www-form-urlencoded',\r\n");
      out.write("      },\r\n");
      out.write("      body: 'inputValue=' + encodeURIComponent(inputValue),\r\n");
      out.write("    })\r\n");
      out.write("      .then(response => response.json())\r\n");
      out.write("      .then(data => {\r\n");
      out.write("        alert(data.message);\r\n");
      out.write("        alert('Record added successfully!');\r\n");
      out.write("        document.getElementById(\"inputValue\").value = \"\";\r\n");
      out.write("        location.reload();\r\n");
      out.write("      })	\r\n");
      out.write("      .catch(error => {\r\n");
      out.write("        console.error('Error:', error);\r\n");
      out.write("      });\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  function redirectToAddRecordPage() {\r\n");
      out.write("    window.location.href = 'addrecord.jsp';\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  // Fetch analytics data on page load\r\n");
      out.write("  fetchSleepAnalytics();\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("      </head>\r\n");
      out.write("\r\n");
      out.write("      <body>\r\n");
      out.write("  <div class=\"sidenav\">\r\n");
      out.write("    <a href=\"#\" style=\"padding-bottom: 100px;padding-left: 10px;\"><img style=\"width: 95%;filter: brightness(1);\" src=\"logo.png\"></a>\r\n");
      out.write("    <a class=\"active\" href=\"index2.jsp\"><img src=\"dashboard.png\"></a>\r\n");
      out.write("    <a href=\"add.jsp\"><img src=\"add.png\"></a>\r\n");
      out.write("    <a href=\"anal.jsp\"><img src=\"anal.png\"></a>\r\n");
      out.write("    <a href=\"info.jsp\"><img src=\"info.png\"></a>\r\n");
      out.write("  </div>\r\n");
      out.write("        <div class=\"main\">\r\n");
      out.write("        \r\n");
      out.write("          <h2 style=\"font-weight: 400;\">Hi! This is <b>Vita+</b></h2>\r\n");
      out.write("          <p style=\"font-weight: bold;font-style:italic;font-size: 20px;\">How are you feeling right now? I am all ears!\r\n");
      out.write("          </p>\r\n");
      out.write("          <form class=\"container\" onsubmit=\"submitForm(); return false;\" method=\"post\">\r\n");
      out.write("            <input id=\"inputValue\" name=\"inputValue\" class=\"moodenter\" type=\"text\" required>\r\n");
      out.write("            <button type=\"submit\" class=\"subbtn\">SUBMIT</button>\r\n");
      out.write("          </form><br><br>\r\n");
      out.write("          <div class=\"analytics_container\">\r\n");
      out.write("<div class=\"pie\">\r\n");
      out.write("	  <iframe src=\"chart.jsp\" class=\"chartFrame\" frameborder=\"0\" width=\"100%\" height=\"100%\"></iframe>\r\n");
      out.write("	  <p class=\"md\">Mood<br>Distribution</p>\r\n");
      out.write("	  \r\n");
      out.write("</div>\r\n");
      out.write("            <div class=\"count\">\r\n");
      out.write("              <div class=\"counts\">\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                  <img class=\"count-icon\" src=\"sleep.png\">\r\n");
      out.write("                  <p class=\"count-text\">You've Slept</p><br>\r\n");
      out.write("                  <p class=\"count-count\">\r\n");
      out.write("                    ");
 
                    int totalHoursSlept=SleepCalculator.calculateSleepHoursForWeek(); out.print(totalHoursSlept+ " hours" ); 
                    int sleeppercent=(totalHoursSlept*100)/50; 
      out.write("\r\n");
      out.write("                      <p style=\"font-size:11px;margin-bottom:-15px\">out 50 hours this week.</p></p>	\r\n");
      out.write("                  <br>\r\n");
      out.write("                  <div class=\"pbbg\">\r\n");
      out.write("                    <div class=\"pb\" style=\"width: ");
      out.print(sleeppercent );
      out.write("%;max-width:100%;min-width:0%\"></div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                  <img class=\"count-icon\" src=\"food.png\">\r\n");
      out.write("                  <p class=\"count-text\">You've Eaten</p><br>\r\n");
      out.write("                  <p class=\"count-count\">\r\n");
      out.write("                    ");
 
                    int totalCalories=CaloriesCalculator.calculateTotalCalories(); out.print(totalCalories + " calories"
                      ); int caloriepercent=(totalCalories*100)/2000; 
      out.write("\r\n");
      out.write("                      <p style=\"font-size:11px;margin-bottom:-15px\">out 2000 calories today.</p>\r\n");
      out.write("                  </p><br>\r\n");
      out.write("                  <div class=\"pbbg\">\r\n");
      out.write("                    <div class=\"pb\" style=\"width: ");
      out.print(caloriepercent );
      out.write("%;max-width:100%\"></div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                  <img class=\"count-icon\" src=\"ill.png\">\r\n");
      out.write("                  <p class=\"count-text\">You got ill</p><br>\r\n");
      out.write("                  <p class=\"count-count\">\r\n");
      out.write("                    ");
 int totalHoursIll=IllnessCalculator.calculateIllnessHoursForMonth(); out.print(totalHoursIll
                      + " times" ); int illnessPercent=(totalHoursIll * 100) / 10;  
      out.write("\r\n");
      out.write("                      <p style=\"font-size:11px;margin-bottom:-15px\">in this month.</p>\r\n");
      out.write("                  </p><br>\r\n");
      out.write("                  <div class=\"pbbg\">\r\n");
      out.write("                    <div class=\"pb\" style=\"width: ");
      out.print(illnessPercent );
      out.write("%;max-width:100%;min-width:0%\"></div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              ");
 int healthmeter=(3*sleeppercent+5*caloriepercent+2*illnessPercent)/10; 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <div class=\"health-meter\">\r\n");
      out.write("                  <p class=\"count-text\">Health Meter</p><br>\r\n");
      out.write("                  <p class=\"count-count\" style=\"font-size:11px;margin-top:-20px\">\r\n");
      out.write("                    ");
out.print(healthmeter + "%" );
      out.write(" - This is your cumulative health percent.\r\n");
      out.write("                  </p>\r\n");
      out.write("                  </p>\r\n");
      out.write("                  <div class=\"pbbg\" style=\"height: 5%;\">\r\n");
      out.write("                    <div class=\"pb\" style=\"width: ");
      out.print(healthmeter );
      out.write("%;max-width:100%;min-width:0%\"></div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("      </body>\r\n");
      out.write("\r\n");
      out.write("      </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
